language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - bower install
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != '<%= projectNameQuoteEscaped %>' ]; then cd .. && eval "mv $currentfolder <%= projectNameDoubleQuoteEscaped %>" && cd '<%= projectNameQuoteEscaped %>'; fi

